### ISSUE TITLE
Q: Does this integration support camect_events?

### ISSUE THREAD

**Issue by sameer-git** [Fr3d/camect-ha#5]
I moved to this integration from the previous Camect manual integration. Does this still support triggering `camect_event`. I can't seem to see them getting triggered in HA

**Comment by sameer-git** [comment]
Looks like it is supported based on looking at the logs. But it is running into this error

```
Unknown error receiving event: {'type': 'alert', 'desc': 'Driveway just saw a car.', 'url': 'https://home.camect.com/v2/#hid=<redacated>&cid=<redacted>&ts=<redacted>', 'cam_id': '<redacted>', 'cam_name': 'Driveway', 'detected_obj': ['car'], 'roi': {'contour': [{'point': [{'x': 0.325, 'y': 0.17777778}, {'x': 0.325, 'y': 0.46666667}, {'x': 0.5125, 'y': 0.9777778}, {'x': 0.975, 'y': 0.9777778}, {'x': 0.925, 'y': 0.42222223}, {'x': 0.5875, 'y': 0.17777778}]}], 'object': [{'name': 'car', 'min_size': 0.067390405, 'max_size': 0.21024437, 'contour': [{'point': [{'x': 0.325, 'y': 0.17777778}, {'x': 0.325, 'y': 0.46666667}, {'x': 0.5125, 'y': 0.9777778}, {'x': 0.975, 'y': 0.9777778}, {'x': 0.925, 'y': 0.42222223}, {'x': 0.575, 'y': 0.17777778}]}], 'movement_trace': {'point': [{'x': 0.80733496, 'y': 0.822303}, {'x': 0.8016075, 'y': 0.7980528}, {'x': 0.7920629, 'y': 0.78136057}, {'x': 0.7833706, 'y': 0.7692803}, {'x': 0.7732292, 'y': 0.7534536}, {'x': 0.7592765, 'y': 0.7272912}, {'x': 0.7449585, 'y': 0.71317136}, {'x': 0.710356, 'y': 0.7073351}, {'x': 0.68915355, 'y': 0.6893182}, {'x': 0.6643289, 'y': 0.6458955}, {'x': 0.6421481, 'y': 0.59224725}, {'x': 0.6204254, 'y': 0.5545256}, {'x': 0.5960809, 'y': 0.5127048}, {'x': 0.57146895, 'y': 0.4789873}, {'x': 0.53698623, 'y': 0.43181688}, {'x': 0.51040673, 'y': 0.40923756}, {'x': 0.48883402, 'y': 0.38279617}, {'x': 0.4691721, 'y': 0.36088634}, {'x': 0.45127696, 'y': 0.33790123}]}, 'vehicle_status': 2}]}}. Error was: Detected that custom integration 'camect' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/camect/camecthub.py, line 223: self.hass.bus.async_fire(ATTR_CAMECT_EVENT, data). Please report it to the author of the 'camect' custom integration.
```

**Comment by sameer-git** [comment]
There is already an open issue for this - https://github.com/Fr3d/camect-ha/issues/4

**Comment by epleypa** [comment]
Once fixed, events can be seen in Developer Tools > Events by subscribing to topic `camect_event`.

Event will look something like this, which will allow you to write a template sensor to extract the event. I don't have alerts on for dogs on this camera, but it looks like the specific event saw a person walking a dog and identified where in the image they were each located. Pretty cool.
```
event_type: camect_event
data:
  device_id: camera.camect_<cam_id>
  type: alert
  raw_data:
    type: alert
    desc: Front Yard just saw a person.
    url: >-
      https://home.camect.com/v2/<redacted>
    cam_id: <cam_id>
    cam_name: Front Yard
    detected_obj:
      - person
    roi:
      contour:
        - point:
            - x: 0.85
              "y": 0.7111111
            - x: 0.775
              "y": 0.4888889
            - x: 0.8375
              "y": 0.31111112
            - x: 0.6125
              "y": 0.2888889
            - x: 0.6
              "y": 0.42222223
            - x: 0.4625
              "y": 0.44444445
            - x: 0.35
              "y": 0.31111112
            - x: 0.05
              "y": 0.33333334
            - x: 0.2375
              "y": 0.42222223
            - x: 0.025
              "y": 0.46666667
            - x: 0.2
              "y": 0.82222223
            - x: 0.4875
              "y": 0.73333335
            - x: 0.6875
              "y": 0.8666667
      object:
        - name: person
          min_size: 0.0010830224
          max_size: 0.026844101
          contour:
            - point:
                - x: 0.8375
                  "y": 0.31111112
                - x: 0.6125
                  "y": 0.2888889
                - x: 0.6125
                  "y": 0.42222223
                - x: 0.025
                  "y": 0.46666667
                - x: 0.025
                  "y": 0.5777778
                - x: 0.175
                  "y": 0.73333335
                - x: 0.8125
                  "y": 0.75555557
                - x: 0.775
                  "y": 0.44444445
          movement_trace:
            point:
              - x: 0.039997872
                "y": 0.49198788
              - x: 0.065485016
                "y": 0.59786576
              - x: 0.052267984
                "y": 0.56440353
              - x: 0.115517214
                "y": 0.5659131
              - x: 0.15989065
                "y": 0.5928003
              - x: 0.20520209
                "y": 0.60191983
              - x: 0.29139608
                "y": 0.60010666
              - x: 0.33616903
                "y": 0.60092264
              - x: 0.39826787
                "y": 0.60111356
              - x: 0.5714152
                "y": 0.6404573
              - x: 0.6039599
                "y": 0.6215404
              - x: 0.6844646
                "y": 0.63012207
              - x: 0.73210317
                "y": 0.64820135
              - x: 0.76925564
                "y": 0.6313615
              - x: 0.63116354
                "y": 0.36688673
              - x: 0.6659889
                "y": 0.357645
              - x: 0.6966649
                "y": 0.39352995
              - x: 0.7281366
                "y": 0.39860517
              - x: 0.78696775
                "y": 0.36356193
              - x: 0.8279582
                "y": 0.3669541
        - name: person
          min_size: 0.00086986844
          max_size: 0.0046214475
          contour:
            - point:
                - x: 0.05
                  "y": 0.33333334
                - x: 0.05
                  "y": 0.4
                - x: 0.225
                  "y": 0.4
                - x: 0.2625
                  "y": 0.46666667
                - x: 0.35
                  "y": 0.46666667
                - x: 0.35
                  "y": 0.31111112
          movement_trace:
            point:
              - x: 0.05759544
                "y": 0.3848253
              - x: 0.088227265
                "y": 0.38807175
              - x: 0.11370046
                "y": 0.3790351
              - x: 0.124689676
                "y": 0.3777489
              - x: 0.14489752
                "y": 0.37061733
              - x: 0.1789371
                "y": 0.37218183
              - x: 0.1966117
                "y": 0.37045217
              - x: 0.24089456
                "y": 0.3663136
              - x: 0.28669393
                "y": 0.4197865
              - x: 0.33845955
                "y": 0.40259105
        - name: dog
          min_size: 0.0009748051
          max_size: 0.014095104
          contour:
            - point:
                - x: 0.0375
                  "y": 0.5777778
                - x: 0.2125
                  "y": 0.6888889
                - x: 0.2
                  "y": 0.82222223
                - x: 0.5375
                  "y": 0.7111111
                - x: 0.5375
                  "y": 0.8666667
                - x: 0.6875
                  "y": 0.8666667
                - x: 0.85
                  "y": 0.7111111
                - x: 0.4375
                  "y": 0.6666667
                - x: 0.3125
                  "y": 0.44444445
                - x: 0.25
                  "y": 0.6
          movement_trace:
            point:
              - x: 0.070285805
                "y": 0.6181533
              - x: 0.096259534
                "y": 0.6257951
              - x: 0.13450718
                "y": 0.6282439
              - x: 0.17601836
                "y": 0.6339278
              - x: 0.20957115
                "y": 0.65122396
              - x: 0.23327056
                "y": 0.6524678
              - x: 0.25606012
                "y": 0.6534556
              - x: 0.32195812
                "y": 0.6635269
              - x: 0.29102576
                "y": 0.5984981
              - x: 0.395476
                "y": 0.6714295
              - x: 0.23100151
                "y": 0.7974049
              - x: 0.5589054
                "y": 0.67887527
              - x: 0.58765644
                "y": 0.66998243
              - x: 0.6207003
                "y": 0.6771081
              - x: 0.58031654
                "y": 0.8256726
              - x: 0.60163164
                "y": 0.8332237
              - x: 0.6264987
                "y": 0.8273777
              - x: 0.6472887
                "y": 0.8312245
              - x: 0.7772875
                "y": 0.6883488
              - x: 0.8155572
                "y": 0.69193184
origin: LOCAL
time_fired: "2024-06-14T18:18:41.994212+00:00"
```

**Comment by sameer-git** [comment]
Got this work with the previous [PR](https://github.com/Fr3d/camect-ha/pull/6) deployed locally.

One thing to note, is that the fields have changed and you need to deref `raw_data`.  This is what my automation that listens for these events look like:

```
- id: 'Motion detected'
  alias: Motion detected
  description: 'Sends a notification when motion is detected'
  trigger:
    platform: event
    event_type: camect_event
    event_data:
      type: alert
  action:
    service: script.notify_pushover_samfar
    data_template:
      message: '{{ trigger.event.data.raw_data[''desc''] }}'
      url: '{{ trigger.event.data.raw_data[''url''] }}'
```
